spring.application.name=store-api
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.path=/h2-console
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

key=myLongSuperSecretKeyForMyStoreApiApplication